import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
} from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import api from "./services/api";
import { MaterialIcons } from "@expo/vector-icons";
import * as Sharing from "expo-sharing";
import * as Print from "expo-print";

export default function TreatmentScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();

  const disease = params.disease as string;
  const severity = parseFloat(params.severity as string);

  const [language, setLanguage] = useState<
    "English" | "Telugu" | "Hindi"
  >("English");
  const [treatment, setTreatment] = useState("");
  const [loading, setLoading] = useState(false);

  /* ================= FETCH TREATMENT ================= */

  const fetchTreatment = async () => {
    setLoading(true);
    setTreatment("");

    try {
      const response = await api.get("/get-treatment/", {
        params: {
          disease_name: disease,
          severity: severity,
          language: language,
        },
      });

      setTreatment(response.data.treatment_plan);
    } catch (error) {
      setTreatment("❌ Failed to fetch treatment plan.");
    } finally {
      setLoading(false);
    }
  };

  /* ================= PDF DOWNLOAD ================= */

  const generateHTML = () => {
    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 16px;
              color: #212121;
            }
            h1 {
              text-align: center;
              color: #2e7d32;
              margin-bottom: 4px;
            }
            h3 {
              text-align: center;
              color: #4e6e4e;
              margin-top: 0;
            }
            .info-box {
              background-color: #f1f8e9;
              padding: 12px;
              border-radius: 8px;
              margin-top: 16px;
              margin-bottom: 16px;
            }
            .section {
              margin-top: 18px;
            }
            p {
              font-size: 14px;
              line-height: 1.6;
              margin-bottom: 8px;
            }
            ul {
              margin-left: 18px;
            }
            li {
              margin-bottom: 6px;
            }
            footer {
              margin-top: 30px;
              text-align: center;
              font-size: 12px;
              color: #757575;
            }
          </style>
        </head>
        <body>
          <h1>🌿 AgroDoctor</h1>
          <h3>AI-Powered Treatment Advisory</h3>

          <div class="info-box">
            <p><strong>Disease:</strong> ${disease}</p>
            <p><strong>Severity:</strong> ${severity}</p>
            <p><strong>Language:</strong> ${language}</p>
          </div>

          <div class="section">
            ${treatment
              .replace(/## (.*)/g, "<h2>$1</h2>")
              .replace(/\* \*\*(.*?)\*\*/g, "<p><strong>$1</strong></p>")
              .replace(/\* (.*)/g, "<li>$1</li>")
              .replace(/\n/g, "<br/>")}
          </div>

          <footer>
            Generated by AgroDoctor AI • For educational & advisory purposes only
          </footer>
        </body>
      </html>
    `;
  };

  const downloadTreatmentAsPDF = async () => {
    try {
      if (!treatment) {
        Alert.alert("Error", "No treatment available to download");
        return;
      }

      const html = generateHTML();

      const { uri } = await Print.printToFileAsync({
        html,
        base64: false,
      });

      await Sharing.shareAsync(uri);
    } catch (error) {
      console.log("PDF error:", error);
      Alert.alert("Error", "Failed to generate PDF");
    }
  };

  /* ================= UI ================= */

  return (
    <View style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>💊 Treatment Plan</Text>
        <Text style={styles.subtitle}>
          Personalized medication & care guidance
        </Text>

        {/* LANGUAGE SELECTION */}
        <View style={styles.langRow}>
          {["English", "Telugu", "Hindi"].map((lang) => (
            <TouchableOpacity
              key={lang}
              style={[
                styles.langBtn,
                language === lang && styles.langActive,
              ]}
              onPress={() => setLanguage(lang as any)}
            >
              <Text style={styles.langText}>{lang}</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* FETCH BUTTON */}
        <TouchableOpacity style={styles.primaryButton} onPress={fetchTreatment}>
          <MaterialIcons name="medical-services" size={20} color="#fff" />
          <Text style={styles.primaryButtonText}>Get Treatment Plan</Text>
        </TouchableOpacity>

        {/* LOADING */}
        {loading && (
          <View style={styles.loaderBox}>
            <ActivityIndicator size="large" color="#2e7d32" />
            <Text style={styles.loadingText}>
              Generating treatment plan...
            </Text>
          </View>
        )}

        {/* RESULT */}
        {!loading && treatment !== "" && (
          <>
            <ScrollView style={styles.card}>
              <Text style={styles.treatmentText}>{treatment}</Text>
            </ScrollView>

            {/* DOWNLOAD */}
            <TouchableOpacity
              style={styles.downloadButton}
              onPress={downloadTreatmentAsPDF}
            >
              <MaterialIcons name="download" size={20} color="#fff" />
              <Text style={styles.downloadButtonText}>
                Download as PDF
              </Text>
            </TouchableOpacity>
          </>
        )}

        {/* BACK */}
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <MaterialIcons name="arrow-back" size={20} color="#fff" />
          <Text style={styles.backButtonText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

/* ================= STYLES ================= */

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f4f9f4" },
  content: { flex: 1, justifyContent: "center", padding: 20 },

  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#1b5e20",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#4e6e4e",
    textAlign: "center",
    marginBottom: 20,
  },

  langRow: { flexDirection: "row", marginBottom: 16 },
  langBtn: {
    flex: 1,
    marginHorizontal: 4,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#e0e0e0",
    alignItems: "center",
  },
  langActive: { backgroundColor: "#a5d6a7" },
  langText: { fontWeight: "600" },

  primaryButton: {
    flexDirection: "row",
    backgroundColor: "#2e7d32",
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },

  loaderBox: { alignItems: "center", marginVertical: 20 },
  loadingText: { marginTop: 8, color: "#4e6e4e" },

  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    maxHeight: 300,
    marginBottom: 10,
  },
  treatmentText: { fontSize: 15, lineHeight: 22 },

  downloadButton: {
    flexDirection: "row",
    backgroundColor: "#1b5e20",
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  downloadButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },

  backButton: {
    flexDirection: "row",
    backgroundColor: "#9e9e9e",
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
});
