import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  StatusBar
} from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Sharing from "expo-sharing";
import * as Print from "expo-print";
import { MaterialIcons, Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import api from "./services/api";
import { useTheme } from "../context/ThemeContext";

export default function TreatmentScreen() {
  const router = useRouter();
  const { colors, isDark } = useTheme();
  const params = useLocalSearchParams();

  const disease = params.disease as string;
  const severity = parseFloat(params.severity as string);

  const [language, setLanguage] = useState<"English" | "Telugu" | "Hindi">("English");
  const [treatment, setTreatment] = useState("");
  const [loading, setLoading] = useState(false);

  /* ================= FETCH TREATMENT ================= */

  const fetchTreatment = async () => {
    setLoading(true);
    setTreatment("");

    try {
      const response = await api.get("/get-treatment/", {
        params: {
          disease_name: disease,
          severity: severity,
          language: language,
        },
      });

      setTreatment(response.data.treatment_plan);
    } catch (error) {
      Alert.alert("Error", "Failed to connect to AI service. Please try again.");
      setTreatment("");
    } finally {
      setLoading(false);
    }
  };

  /* ================= PDF DOWNLOAD ================= */

  const generateHTML = () => {
    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            body { font-family: Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
            h1 { text-align: center; color: #2e7d32; }
            .badge { background: #e8f5e9; padding: 10px; border-radius: 8px; text-align: center; margin: 20px 0; }
            p, li { line-height: 1.6; font-size: 14px; }
            strong { color: #1b5e20; }
            footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
          </style>
        </head>
        <body>
          <h1>🌿 AgroDoctor Advisory</h1>
          <div class="badge">
            <p><strong>Disease:</strong> ${disease} | <strong>Severity:</strong> ${severity}%</p>
            <p><strong>Language:</strong> ${language}</p>
          </div>
          <hr/>
          <div>
            ${treatment
              .replace(/## (.*)/g, "<h2>$1</h2>")
              .replace(/\* \*\*(.*?)\*\*/g, "<p><strong>$1</strong></p>")
              .replace(/\* (.*)/g, "<li>$1</li>")
              .replace(/\n/g, "<br/>")}
          </div>
          <footer>Generated by AgroDoctor AI • Consult an expert for critical decisions.</footer>
        </body>
      </html>
    `;
  };

  const downloadTreatmentAsPDF = async () => {
    try {
      if (!treatment) {
        Alert.alert("Empty Plan", "Please generate a treatment plan first.");
        return;
      }

      const html = generateHTML();
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri);
    } catch (error) {
      console.log("PDF error:", error);
      Alert.alert("Export Failed", "Could not generate PDF file.");
    }
  };

  /* ================= UI ================= */

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <StatusBar barStyle={isDark ? "light-content" : "dark-content"} />

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        
        {/* Header */}
        <View style={styles.header}>
          <View style={[styles.iconCircle, { backgroundColor: colors.primary + '20' }]}>
            <MaterialIcons name="healing" size={36} color={colors.primary} />
          </View>
          <Text style={[styles.title, { color: colors.text }]}>Treatment Plan</Text>
          <Text style={[styles.subtitle, { color: colors.icon }]}>
            AI-generated advice for {disease}
          </Text>
        </View>

        {/* Language Selector */}
        <Text style={[styles.sectionLabel, { color: colors.text }]}>Select Language:</Text>
        <View style={[styles.langContainer, { backgroundColor: colors.card, borderColor: colors.border }]}>
          {["English", "Telugu", "Hindi"].map((lang) => (
            <TouchableOpacity
              key={lang}
              style={[
                styles.langBtn,
                language === lang && { backgroundColor: colors.primary },
              ]}
              onPress={() => setLanguage(lang as any)}
            >
              <Text
                style={[
                  styles.langText,
                  { color: language === lang ? "#fff" : colors.text },
                ]}
              >
                {lang}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Fetch Button */}
        {!treatment && (
          <TouchableOpacity 
            style={[styles.fetchBtn, { backgroundColor: colors.primary }]} 
            onPress={fetchTreatment}
            disabled={loading}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <>
                <MaterialCommunityIcons name="robot-outline" size={24} color="#fff" style={{ marginRight: 8 }} />
                <Text style={styles.fetchBtnText}>Generate with AI</Text>
              </>
            )}
          </TouchableOpacity>
        )}

        {/* Loading State */}
        {loading && (
          <View style={styles.loaderBox}>
            <Text style={[styles.loadingText, { color: colors.icon }]}>Consulting AgroDoctor AI...</Text>
          </View>
        )}

        {/* Result Area */}
        {treatment !== "" && (
          <View style={[styles.resultContainer, { backgroundColor: colors.card, borderColor: isDark ? colors.border : 'transparent' }]}>
            <ScrollView nestedScrollEnabled style={{ maxHeight: 350 }}>
              <Text style={[styles.treatmentText, { color: colors.text }]}>{treatment}</Text>
            </ScrollView>
          </View>
        )}

        {/* Action Buttons */}
        {treatment !== "" && (
          <View style={styles.actionRow}>
            <TouchableOpacity
              style={[styles.actionBtn, { backgroundColor: '#444' }]} // Dark button for contrast
              onPress={downloadTreatmentAsPDF}
            >
              <MaterialIcons name="picture-as-pdf" size={20} color="#fff" style={{ marginRight: 8 }} />
              <Text style={styles.actionBtnText}>Save PDF</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.actionBtn, { backgroundColor: colors.primary }]}
              onPress={fetchTreatment} // Regenerate
            >
              <Ionicons name="refresh" size={20} color="#fff" style={{ marginRight: 8 }} />
              <Text style={styles.actionBtnText}>Regenerate</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Back Button */}
        <TouchableOpacity style={[styles.backBtn, { marginTop: 20 }]} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={20} color={colors.icon} />
          <Text style={[styles.backBtnText, { color: colors.icon }]}>Go Back</Text>
        </TouchableOpacity>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  iconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
    marginLeft: 5,
  },
  langContainer: {
    flexDirection: "row",
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    marginBottom: 25,
  },
  langBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
  },
  langText: {
    fontWeight: "600",
    fontSize: 14,
  },
  fetchBtn: {
    flexDirection: "row",
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#2E7D32",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  fetchBtnText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  loaderBox: {
    marginTop: 20,
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    fontStyle: "italic",
  },
  resultContainer: {
    marginTop: 20,
    borderRadius: 16,
    padding: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    borderWidth: 1,
    borderColor: 'transparent',
  },
  treatmentText: {
    fontSize: 15,
    lineHeight: 24,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    gap: 15,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  actionBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  backBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  backBtnText: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
});